- name: AWX Demo for Infinibox
  hosts: localhost
  collections: infinidat.infinibox
  connection: local
  gather_facts: no

  tasks:
  - name: Create new host
    infini_host:
      name: "{{host_name}}"
      user: "{{user}}"
      password: "{{password}}"
      system: "{{array_ip}}"
