- name: AWX Demo for Infinibox
  hosts: localhost
  collections: infinidat.infinibox
  connection: local
  gather_facts: no

  tasks:
  - name: Export NFS Filesystem
    infini_export:
      name: "{{export_fs}}"
      filesystem: "{{filesystem}}"
      state: present
      user: "{{user}}"
      password: "{{password}}"
      system: "{{array_ip}}"
