- name: AWX Demo for Infinibox
  hosts: localhost
  collections: infinidat.infinibox
  connection: local
  gather_facts: no

  tasks:
  - name: Export FS to NFS client
    infini_export_client:
      client: "{{client_ip}}"
      access_mode: "{{access}}"
      no_root_squash: true
      export: "{{exp_path}}"
      state: present
      user: "{{user}}"
      password: "{{password}}"
      system: "{{array_ip}}"
