- name: AWX Demo for Infinibox
  hosts: localhost
  collections: infinidat.infinibox
  connection: local
  gather_facts: no

  tasks:
  - name: Map a volume to an existing host
    infini_map:
      host: "{{host_name}}"
      volume: "{{vol_name}}"
      state: present
      user: "{{user}}"
      password: "{{password}}"
      system: "{{array_ip}}"
